### ISSUE TITLE
Gitignore node_modules

### ISSUE THREAD

**Issue by nareddyt** [GTBitsOfGood/bootcamp-2019#26]
We need to git ignore all `node_modules`. This folder should be ignored in all directories in this repo.

**Comment by themroats** [comment]
I just added it to the master's .gitignore, along with .idea for anyone else that uses JetBrains for this stuff. If everyone just commits deleting node_modules then everything should be good.

**Comment by nareddyt** [comment]
Nice! I can close this issue manually since your PR was merged to master.

As a tip, it's good practice to reference this issue number (#26, found in the title above) in the Pull Request that fixes it. That allows github to link the PR to the Issue and will automatically close the issue once the PR is merged. All you have to do is include something like "Closes #26" in the description at the beginning of your PR!

I'll manually reference your PR from this Issue (with the line below) since it's already merged :)

Resolved via #31
